title: Picot Canvas
description: Picot Canvas is an open source driver for e-ink frames.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
github:
  zip_url: https://github.com/fbarresi/PicotCanvas/archive/refs/heads/main.zip
  tar_url: https://github.com/fbarresi/PicotCanvas/archive/refs/heads/main.zip
